name: Build App

on:
  push:
    branches: [main]
    paths: [.github/**, app/**]
  pull_request:
    branches: [main]
    paths: [.github/**, app/**]

jobs:
  test:
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/antoncuranz/playwright-jazz-docker:latest
      options: --user 1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: "true"

      - name: Install dependencies
        run: npm ci
        working-directory: ./app

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./app

      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: app/tests/report/
          retention-days: 7

      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: app/tests/results/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: |
            ghcr.io/antoncuranz/kompass/app:${{ steps.vars.outputs.sha_shortÂ }}
            ${{ github.event_name == 'push' && 'ghcr.io/antoncuranz/kompass/app:latest' || '' }}
