name: Playwright Tests

on:
  push:
    branches: [main]
    paths: [app/**]
  pull_request:
    branches: [main]
    paths: [app/**]

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/antoncuranz/playwright-jazz-docker:latest
      options: --user 1001

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm i
        working-directory: ./app

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./app

      - uses: actions/upload-artifact@v5
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: app/playwright-report/
          retention-days: 30
