name: Build server-worker

on:
  push:
    branches: [main]
    paths: [.github/**, server-worker/**]
  pull_request:
    branches: [main]
    paths: [.github/**, server-worker/**]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ./server-worker

      - name: Run linter
        run: bun lint
        working-directory: ./server-worker

      - name: Run tests
        run: bun run test
        working-directory: ./server-worker

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push server-worker
        uses: docker/build-push-action@v6
        with:
          context: server-worker
          push: true
          tags: |
            ghcr.io/antoncuranz/kompass/server-worker:${{ steps.vars.outputs.sha_shortÂ }}
            ${{ github.event_name == 'push' && 'ghcr.io/antoncuranz/kompass/server-worker:latest' || '' }}
