name: Build sync-server

on:
  push:
    branches: [main]
    paths: [.github/**, sync-server/**]
  pull_request:
    branches: [main]
    paths: [.github/**, sync-server/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract JAZZ_VERSION
        id: jazz_version
        run: |
          VERSION=$(grep 'ARG JAZZ_VERSION=' sync-server/Dockerfile | sed 's/.*JAZZ_VERSION="\(.*\)"/\1/')
          echo "found version $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push sync-server
        uses: docker/build-push-action@v6
        with:
          context: sync-server
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/antoncuranz/kompass/sync-server:latest
            ghcr.io/antoncuranz/kompass/sync-server:${{ steps.jazz_version.outputs.version }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
