name: Build Transportation API

on:
  push:
    branches: [main]
    paths: [.github/**, transportation-api/**]
  pull_request:
    branches: [main]
    paths: [.github/**, transportation-api/**]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        working-directory: ./transportation-api
        run: go get .

      - name: Run integration tests
        working-directory: ./transportation-api
        run: go test -v ./integration-test/...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push transportation-api
        uses: docker/build-push-action@v6
        with:
          context: transportation-api
          push: true
          tags: |
            ghcr.io/antoncuranz/kompass/transportation-api:${{ github.sha }}
            ${{ github.event_name == 'push' && 'ghcr.io/antoncuranz/kompass/transportation-api:latest' || '' }}
